import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "mobilux",
  description: "Generated by Sodiqjon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="fixed top-0 left-0 right-0 z-10">
          <Header />
        </header>
        <main className="flex-1 mt-16"> {/* Adjust the margin-top based on header height */}
          {children}
        </main>
        {/* Footer with conditional positioning based on screen size */}
        <footer className="lg:relative lg:bottom-0 lg:left-0 lg:right-0 fixed bottom-0 w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
